# Site settings
title: Goleki.js
email: akiddcode@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Jquery Plugin for Search with autocomplete be easy.
baseurl: "/goleki" # the subpath of your site, e.g. /blog/
url: "http://antoniputra.github.io" # the base hostname & protocol for your site
twitter_username: antoni_putra12
github_username:  antoniputra

# Build settings
markdown: kramdown

sass: 
    style: compressed